from __future__ import annotations

from typing import Protocol

from salesperson.models import DealRecord, SalesBehavior, UsageRecord, Website, WebsiteUser


class PlatformRepository(Protocol):
    def save_website(self, website: Website) -> None: ...

    def get_website(self, website_id: str) -> Website: ...

    def list_api_key_hashes(self) -> dict[str, str]: ...

    def save_user(self, user: WebsiteUser) -> None: ...

    def get_user(self, website_id: str, user_id: str) -> WebsiteUser: ...

    def next_user_number(self, website_id: str) -> int: ...

    def update_behavior(self, website_id: str, behavior: SalesBehavior) -> SalesBehavior: ...

    def append_usage(self, usage: UsageRecord) -> UsageRecord: ...

    def append_deal(self, deal: DealRecord) -> DealRecord: ...

    def list_usage(self, website_id: str) -> list[UsageRecord]: ...

    def list_deals(self, website_id: str) -> list[DealRecord]: ...

    def count_users(self, website_id: str) -> int: ...

    def website_exists(self, website_id: str) -> bool: ...
